package mitame.euler;
/*
  Problem 2: Even Fibonacci numbers

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class Euler002
{
  public static void main(String[] args) {
    int n0 = 0;
    int n1 = 1;
    int n2 = 1;
    int sum = 0;
    while (n1 < 4e6) {
      n0 = n1;
      n1 = n2;
      n2 = n1 + n0;

      if (n2 % 2 == 0)
        sum += n2;
    }
    System.out.println(sum);
  }
}